### ISSUE TITLE
TDP & Boost issue

### ISSUE THREAD

**Issue by XeonKyle** [thesacredmoocow/g14control-r2#2]
On my system (R9 4900 & 2060MQ), adjusting the TDP value does not affect CPU Package Power as reported by HWiNFO. With boost disabled, package power hovers right around 20W no matter the specified TDP value.
I am also unable to get it to boost at all with Efficient Aggressive irrespective of set TDP, only Aggressive, which reports ~55W package power.

**Comment by XeonKyle** [comment]
heres a .txt of my config.yml, its very possible I just goofed somewhere
[config.txt](https://github.com/thesacredmoocow/g14control-r2/files/5196338/config.txt)

**Comment by aredden** [comment]
@XeonKyle Are you looking at the HWiNFO system summary window? If so, that is the wattage rating of the cpu, not the current wattage. To see the current wattage you would look at the sensor data and find the row containing "CPU Package Power (SMU)" which will show a much lower number, but is more accurately representing (some) of the current wattage of the cpu.

**Comment by XeonKyle** [comment]
@aredden yes, I was referencing CPU Package Power (SMU) sensor data.
![example](https://user-images.githubusercontent.com/71027480/92631735-c78f4a80-f29f-11ea-8306-952b5baa2640.PNG)

**Comment by aredden** [comment]
That is interesting. Mine goes up much higher actually (I didn't realize you were doing a benchmark). Do you still have Armory Crate installed? I am just guessing here, but it could be that Armory Crate is making automatic adjustments and modifying the settings that G14Control modifies? 

If that is not the case, then there must be something else that is causing ryzenadj.exe to run. If you are comfortable with command line, try running this in admin cmd in the same directory as ryzenadj.exe, which is under C:/temp..
```cmd
./ryzenadj.exe -a 45000 -b 45000
```
This is the same command that is used in the python source code. Check and see if it runs. If it does, try the test again and see what the outcome is.

**Comment by XeonKyle** [comment]
Ran it and had the same result of no boost or tdp control, but curiously I tried using the "turbo" power plan instead of "performance" on the profile, and both Efficient Aggressive and the TDP control now work as intended. I'll write out a fan profile for it and consider it done. Thanks for your help & work on this great app :)
